### ISSUE TITLE
Broken schemagen for singular/plural field in NotificationPolicyTimeRestriction

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-opsgenie#57]
### What happened?

It turns out during docs gen we overwrite NotificationPolicyTimeRestrictionRestriction(singular) with the fields for NotificationPolicyTimeRestrictions (plural), and completely omit the fields describing the singular subresource.

[You can observe the upstream documentation correctly showing both fields](https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/notification_policy#argument-reference)

[Our docs are sadly missing the difference](https://www.pulumi.com/registry/packages/opsgenie/api-docs/notificationpolicy/)

### Steps to reproduce

n/a

### Expected Behavior

At the very least, we should not associate fields with the wrong subresource

### Actual Behavior

The documentation is wrong

### Additional context

See https://github.com/pulumi/pulumi-opsgenie/issues/56#issuecomment-1189595635 and related issues.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkodroff** [comment]
After looking at this with @guineveresaenger, the issue runs a little deeper.

In TF: 

* There is a block `[opsgenie_notification_policy.time_restriction.restriction](https://github.com/opsgenie/terraform-provider-opsgenie/blob/master/opsgenie/resource_opsgenie_notification_policy.go#L171-L194)`. It has 4 fields per the schema. It _might_ also be missing `MaxItems: 1` - would need to test in a full program.
* There is also a block `[opsgenie_notification_policy.time_restriction.restrictions](https://github.com/opsgenie/terraform-provider-opsgenie/blob/master/opsgenie/resource_opsgenie_notification_policy.go#L139-L170)`. It has 6 fields per the schema.

In the provider mapping, we have extra config for this resource: https://github.com/pulumi/pulumi-opsgenie/blob/master/provider/resources.go#L117-L131

In Pulumi (linking to the docs because I believe the docs always mirror the schema, even if the descriptions are blank), we only have 1 type to cover the elements of both `NotificationPolicy.timeRestrictions.restriction[]` `NotificationPolicy.timeRestrictions.restrictions[]`. This is incorrect. The former should map to a type with 4 fields, and the latter to a different type with 6 fields.

In other words, the generated schema appears to be incorrect.

Removing the extra config for `opsgenie_notification_policy` will not fix the problem. We can see this because [`opsgenie_alert_policy` has no extra config](https://github.com/pulumi/pulumi-opsgenie/blob/master/provider/resources.go#L174-L176), but [its schema is broken in a different way](https://www.pulumi.com/registry/packages/opsgenie/api-docs/alertpolicy/#alertpolicytimerestriction): There is no `restriction` (singular) option at all. (Also, for what it's worth, the description of `AlertPolicyTimeRestruction.type` is incorrect because of pulumi-terraform-bridge#529.)

To solve this issue, I suggest:

1. See if there's an additional  configuration that can untangle the `restriction` and `restrictions` types so that they each map to separate types for the elements of each array (one with 4 props, another with 6). If not,
2. See if this is potentially a bug in the bridge. At the very least, it would be nice to get a big fat warning there are type names which are in conflict and so suggest what to do to resolve. We could be swallowing an error.
3. See if this is a bug in codegen.

I'm not clear on the impact on end users, though. We'd need to write a program to see what happens if we attempt to use `restriction[]`. I'm guessing the bridge (or possibly the upstream API) will throw an error, but they both might ignore extra, unknown fields.

**Comment by jkodroff** [comment]
@guineveresaenger This might be a better idea: We could rename them on all affected resources to `timeOfDayRestriction` and `weekdayAndTimeOfDayRestriction`, which would be clearer _and_ should generate a correct schema.
